[package]
name = "rjw_2d_render"
version = "0.1.0"
edition = "2024"

[dependencies]
rjw_render = { path = "../rjw_render" }
rjw_atlas = { path = "../rjw_atlas", optional = true }
rjw_transform = { path = "../rjw_transform" }
rjw_color = "0.1.0"
wgpu = "30.0.0"
glam = "0.33.2"
ordered-float = "4.2"
log = "0.4.33"
bytemuck = { version = "1.25.2", features = ["derive"] }

[features]
default = ["rjw_atlas"]
rjw_atlas = ["dep:rjw_atlas"]