[package]
name = "eg260818UI"
version = "0.1.0"
edition = "2024"

[dependencies]
glam = "0.33.2"
rjw_main = { path = "../../crates/rjw_main" }
rjw_render = { path = "../../crates/rjw_render" }
rjw_2d_render = { path = "../../crates/rjw_2d_render" }
rjw_text = { path = "../../crates/rjw_text" }
rjw_transform = { path = "../../crates/rjw_transform" }
rjw_color = { version = "0.1.0", features = ["wgpu"] }
rjw_ui = { path = "../../crates/rjw_ui" }
