use super::{Color, ColorF64};

macro_rules! color_consts {
    ($ty:ident) => {
        #[rustfmt::skip]
        impl $ty {
            pub const ALICEBLUE: Self                   = Self::from_hex_rgb("#F0F8FF");
            pub const ANTIQUEWHITE: Self                = Self::from_hex_rgb("#FAEBD7");
            pub const AQUA: Self                        = Self::from_hex_rgb("#00FFFF");
            pub const AQUAMARINE: Self                  = Self::from_hex_rgb("#7FFFD4");
            pub const AZURE: Self                       = Self::from_hex_rgb("#F0FFFF");
            pub const BEIGE: Self                       = Self::from_hex_rgb("#F5F5DC");
            pub const BISQUE: Self                      = Self::from_hex_rgb("#FFE4C4");
            pub const BLACK: Self                       = Self::from_hex_rgb("#000000");
            pub const BLANCHEDALMOND: Self              = Self::from_hex_rgb("#FFEBCD");
            pub const BLUE: Self                        = Self::from_hex_rgb("#0000FF");
            pub const BLUEVIOLET: Self                  = Self::from_hex_rgb("#8A2BE2");
            pub const BROWN: Self                       = Self::from_hex_rgb("#A52A2A");
            pub const BURLYWOOD: Self                   = Self::from_hex_rgb("#DEB887");
            pub const CADETBLUE: Self                   = Self::from_hex_rgb("#5F9EA0");
            pub const CHARTREUSE: Self                  = Self::from_hex_rgb("#7FFF00");
            pub const CHOCOLATE: Self                   = Self::from_hex_rgb("#D2691E");
            pub const CORAL: Self                       = Self::from_hex_rgb("#FF7F50");
            pub const CORNFLOWERBLUE: Self              = Self::from_hex_rgb("#6495ED");
            pub const CORNSILK: Self                    = Self::from_hex_rgb("#FFF8DC");
            pub const CRIMSON: Self                     = Self::from_hex_rgb("#DC143C");
            pub const CYAN: Self                        = Self::from_hex_rgb("#00FFFF");
            pub const DARKBLUE: Self                    = Self::from_hex_rgb("#00008B");
            pub const DARKCYAN: Self                    = Self::from_hex_rgb("#008B8B");
            pub const DARKGOLDENROD: Self               = Self::from_hex_rgb("#B8860B");
            pub const DARKGRAY: Self                    = Self::from_hex_rgb("#A9A9A9");
            pub const DARKGREEN: Self                   = Self::from_hex_rgb("#006400");
            pub const DARKKHAKI: Self                   = Self::from_hex_rgb("#BDB76B");
            pub const DARKMAGENTA: Self                 = Self::from_hex_rgb("#8B008B");
            pub const DARKOLIVEGREEN: Self              = Self::from_hex_rgb("#556B2F");
            pub const DARKORANGE: Self                  = Self::from_hex_rgb("#FF8C00");
            pub const DARKORCHID: Self                  = Self::from_hex_rgb("#9932CC");
            pub const DARKRED: Self                     = Self::from_hex_rgb("#8B0000");
            pub const DARKSALMON: Self                  = Self::from_hex_rgb("#E9967A");
            pub const DARKSEAGREEN: Self                = Self::from_hex_rgb("#8FBC8F");
            pub const DARKSLATEBLUE: Self               = Self::from_hex_rgb("#483D8B");
            pub const DARKSLATEGRAY: Self               = Self::from_hex_rgb("#2F4F4F");
            pub const DARKTURQUOISE: Self               = Self::from_hex_rgb("#00CED1");
            pub const DARKVIOLET: Self                  = Self::from_hex_rgb("#9400D3");
            pub const DEEPPINK: Self                    = Self::from_hex_rgb("#FF1493");
            pub const DEEPSKYBLUE: Self                 = Self::from_hex_rgb("#00BFFF");
            pub const DIMGRAY: Self                     = Self::from_hex_rgb("#696969");
            pub const DODGERBLUE: Self                  = Self::from_hex_rgb("#1E90FF");
            pub const FIREBRICK: Self                   = Self::from_hex_rgb("#B22222");
            pub const FLORALWHITE: Self                 = Self::from_hex_rgb("#FFFAF0");
            pub const FORESTGREEN: Self                 = Self::from_hex_rgb("#228B22");
            pub const FUCHSIA: Self                     = Self::from_hex_rgb("#FF00FF");
            pub const GAINSBORO: Self                   = Self::from_hex_rgb("#DCDCDC");
            pub const GHOSTWHITE: Self                  = Self::from_hex_rgb("#F8F8FF");
            pub const GOLD: Self                        = Self::from_hex_rgb("#FFD700");
            pub const GOLDENROD: Self                   = Self::from_hex_rgb("#DAA520");
            pub const GRAY: Self                        = Self::from_hex_rgb("#808080");
            pub const GREEN: Self                       = Self::from_hex_rgb("#008000");
            pub const GREENYELLOW: Self                 = Self::from_hex_rgb("#ADFF2F");
            pub const HONEYDEW: Self                    = Self::from_hex_rgb("#F0FFF0");
            pub const HOTPINK: Self                     = Self::from_hex_rgb("#FF69B4");
            pub const INDIANRED: Self                   = Self::from_hex_rgb("#CD5C5C");
            pub const INDIGO: Self                      = Self::from_hex_rgb("#4B0082");
            pub const IVORY: Self                       = Self::from_hex_rgb("#FFFFF0");
            pub const KHAKI: Self                       = Self::from_hex_rgb("#F0E68C");
            pub const LAVENDER: Self                    = Self::from_hex_rgb("#E6E6FA");
            pub const LAVENDERBLUSH: Self               = Self::from_hex_rgb("#FFF0F5");
            pub const LAWNGREEN: Self                   = Self::from_hex_rgb("#7CFC00");
            pub const LEMONCHIFFON: Self                = Self::from_hex_rgb("#FFFACD");
            pub const LIGHTBLUE: Self                   = Self::from_hex_rgb("#ADD8E6");
            pub const LIGHTCORAL: Self                  = Self::from_hex_rgb("#F08080");
            pub const LIGHTCYAN: Self                   = Self::from_hex_rgb("#E0FFFF");
            pub const LIGHTGOLDENRODYELLOW: Self        = Self::from_hex_rgb("#FAFAD2");
            pub const LIGHTGRAY: Self                   = Self::from_hex_rgb("#D3D3D3");
            pub const LIGHTGREEN: Self                  = Self::from_hex_rgb("#90EE90");
            pub const LIGHTPINK: Self                   = Self::from_hex_rgb("#FFB6C1");
            pub const LIGHTSALMON: Self                 = Self::from_hex_rgb("#FFA07A");
            pub const LIGHTSEAGREEN: Self               = Self::from_hex_rgb("#20B2AA");
            pub const LIGHTSKYBLUE: Self                = Self::from_hex_rgb("#87CEFA");
            pub const LIGHTSLATEGRAY: Self              = Self::from_hex_rgb("#778899");
            pub const LIGHTSTEELBLUE: Self              = Self::from_hex_rgb("#B0C4DE");
            pub const LIGHTYELLOW: Self                 = Self::from_hex_rgb("#FFFFE0");
            pub const LIME: Self                        = Self::from_hex_rgb("#00FF00");
            pub const LIMEGREEN: Self                   = Self::from_hex_rgb("#32CD32");
            pub const LINEN: Self                       = Self::from_hex_rgb("#FAF0E6");
            pub const MAGENTA: Self                     = Self::from_hex_rgb("#FF00FF");
            pub const MAROON: Self                      = Self::from_hex_rgb("#800000");
            pub const MEDIUMAQUAMARINE: Self            = Self::from_hex_rgb("#66CDAA");
            pub const MEDIUMBLUE: Self                  = Self::from_hex_rgb("#0000CD");
            pub const MEDIUMORCHID: Self                = Self::from_hex_rgb("#BA55D3");
            pub const MEDIUMPURPLE: Self                = Self::from_hex_rgb("#9370DB");
            pub const MEDIUMSEAGREEN: Self              = Self::from_hex_rgb("#3CB371");
            pub const MEDIUMSLATEBLUE: Self             = Self::from_hex_rgb("#7B68EE");
            pub const MEDIUMSPRINGGREEN: Self           = Self::from_hex_rgb("#00FA9A");
            pub const MEDIUMTURQUOISE: Self             = Self::from_hex_rgb("#48D1CC");
            pub const MEDIUMVIOLETRED: Self             = Self::from_hex_rgb("#C71585");
            pub const MIDNIGHTBLUE: Self                = Self::from_hex_rgb("#191970");
            pub const MINTCREAM: Self                   = Self::from_hex_rgb("#F5FFFA");
            pub const MISTYROSE: Self                   = Self::from_hex_rgb("#FFE4E1");
            pub const MOCCASIN: Self                    = Self::from_hex_rgb("#FFE4B5");
            pub const NAVAJOWHITE: Self                 = Self::from_hex_rgb("#FFDEAD");
            pub const NAVY: Self                        = Self::from_hex_rgb("#000080");
            pub const OLDLACE: Self                     = Self::from_hex_rgb("#FDF5E6");
            pub const OLIVE: Self                       = Self::from_hex_rgb("#808000");
            pub const OLIVEDRAB: Self                   = Self::from_hex_rgb("#6B8E23");
            pub const ORANGE: Self                      = Self::from_hex_rgb("#FFA500");
            pub const ORANGERED: Self                   = Self::from_hex_rgb("#FF4500");
            pub const ORCHID: Self                      = Self::from_hex_rgb("#DA70D6");
            pub const PALEGOLDENROD: Self               = Self::from_hex_rgb("#EEE8AA");
            pub const PALEGREEN: Self                   = Self::from_hex_rgb("#98FB98");
            pub const PALETURQUOISE: Self               = Self::from_hex_rgb("#AFEEEE");
            pub const PALEVIOLETRED: Self               = Self::from_hex_rgb("#DB7093");
            pub const PAPAYAWHIP: Self                  = Self::from_hex_rgb("#FFEFD5");
            pub const PEACHPUFF: Self                   = Self::from_hex_rgb("#FFDAB9");
            pub const PERU: Self                        = Self::from_hex_rgb("#CD853F");
            pub const PINK: Self                        = Self::from_hex_rgb("#FFC0CB");
            pub const PLUM: Self                        = Self::from_hex_rgb("#DDA0DD");
            pub const POWDERBLUE: Self                  = Self::from_hex_rgb("#B0E0E6");
            pub const PURPLE: Self                      = Self::from_hex_rgb("#800080");
            pub const REBECCAPURPLE: Self               = Self::from_hex_rgb("#663399");
            pub const RED: Self                         = Self::from_hex_rgb("#FF0000");
            pub const ROSYBROWN: Self                   = Self::from_hex_rgb("#BC8F8F");
            pub const ROYALBLUE: Self                   = Self::from_hex_rgb("#4169E1");
            pub const SADDLEBROWN: Self                 = Self::from_hex_rgb("#8B4513");
            pub const SALMON: Self                      = Self::from_hex_rgb("#FA8072");
            pub const SANDYBROWN: Self                  = Self::from_hex_rgb("#F4A460");
            pub const SEAGREEN: Self                    = Self::from_hex_rgb("#2E8B57");
            pub const SEASHELL: Self                    = Self::from_hex_rgb("#FFF5EE");
            pub const SIENNA: Self                      = Self::from_hex_rgb("#A0522D");
            pub const SILVER: Self                      = Self::from_hex_rgb("#C0C0C0");
            pub const SKYBLUE: Self                     = Self::from_hex_rgb("#87CEEB");
            pub const SLATEBLUE: Self                   = Self::from_hex_rgb("#6A5ACD");
            pub const SLATEGRAY: Self                   = Self::from_hex_rgb("#708090");
            pub const SNOW: Self                        = Self::from_hex_rgb("#FFFAFA");
            pub const SPRINGGREEN: Self                 = Self::from_hex_rgb("#00FF7F");
            pub const STEELBLUE: Self                   = Self::from_hex_rgb("#4682B4");
            pub const TAN: Self                         = Self::from_hex_rgb("#D2B48C");
            pub const TEAL: Self                        = Self::from_hex_rgb("#008080");
            pub const THISTLE: Self                     = Self::from_hex_rgb("#D8BFD8");
            pub const TOMATO: Self                      = Self::from_hex_rgb("#FF6347");
            pub const TURQUOISE: Self                   = Self::from_hex_rgb("#40E0D0");
            pub const VIOLET: Self                      = Self::from_hex_rgb("#EE82EE");
            pub const WHEAT: Self                       = Self::from_hex_rgb("#F5DEB3");
            pub const WHITE: Self                       = Self::from_hex_rgb("#FFFFFF");
            pub const WHITESMOKE: Self                  = Self::from_hex_rgb("#F5F5F5");
            pub const YELLOW: Self                      = Self::from_hex_rgb("#FFFF00");
            pub const YELLOWGREEN: Self                 = Self::from_hex_rgb("#9ACD32");
            // pub const BLACK: Self           = Self::rgb (        0.0,         0.0,         0.0                );
            // pub const WHITE: Self           = Self::rgb (        1.0,         1.0,         1.0                );
            pub const TRANSPARENT: Self                 = Self::rgba(        0.0,         0.0,         0.0,            0.0);
            // pub const RED: Self             = Self::rgb (        1.0,         0.0,         0.0                );
            // pub const LIME: Self           = Self::rgb (        0.0,         1.0,         0.0                );
            // pub const BLUE: Self            = Self::rgb (        0.0,         0.0,         1.0                );
            // pub const YELLOW: Self          = Self::rgb (        1.0,         1.0,         0.0                );
            // pub const PURPLE: Self          = Self::rgb (        1.0,         0.0,         1.0                );
            // pub const CYAN: Self            = Self::rgb (        0.0,         1.0,         1.0                );
            // pub const AQUA: Self            = Self::rgb (        0.0,         1.0,         1.0                );
        }
    };
}

color_consts!(Color);
color_consts!(ColorF64);

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_color_consts() {
        assert_eq!(Color::RED, Color::from_hex_rgb("#FF0000"));
        assert_eq!(ColorF64::LIME, ColorF64::from_hex_rgb("#00FF00"));
        assert_eq!(Color::BLUE, Color::from_hex_rgb("#0000FF"));
        assert_eq!(ColorF64::WHITE, ColorF64::from_hex_rgb("#FFFFFF"));
        assert_eq!(Color::BLACK, Color::from_hex_rgb("#000000"));
    }
}