use super::{Color, ColorF64};

macro_rules! color_consts {
    ($ty:ident) => {
        #[rustfmt::skip]
        impl $ty {
            pub const CSS_ALICEBLUE: Self                   = Self::from_hex_rgb("#F0F8FF");
            pub const CSS_ANTIQUEWHITE: Self                = Self::from_hex_rgb("#FAEBD7");
            pub const CSS_AQUA: Self                        = Self::from_hex_rgb("#00FFFF");
            pub const CSS_AQUAMARINE: Self                  = Self::from_hex_rgb("#7FFFD4");
            pub const CSS_AZURE: Self                       = Self::from_hex_rgb("#F0FFFF");
            pub const CSS_BEIGE: Self                       = Self::from_hex_rgb("#F5F5DC");
            pub const CSS_BISQUE: Self                      = Self::from_hex_rgb("#FFE4C4");
            pub const CSS_BLACK: Self                       = Self::from_hex_rgb("#000000");
            pub const CSS_BLANCHEDALMOND: Self              = Self::from_hex_rgb("#FFEBCD");
            pub const CSS_BLUE: Self                        = Self::from_hex_rgb("#0000FF");
            pub const CSS_BLUEVIOLET: Self                  = Self::from_hex_rgb("#8A2BE2");
            pub const CSS_BROWN: Self                       = Self::from_hex_rgb("#A52A2A");
            pub const CSS_BURLYWOOD: Self                   = Self::from_hex_rgb("#DEB887");
            pub const CSS_CADETBLUE: Self                   = Self::from_hex_rgb("#5F9EA0");
            pub const CSS_CHARTREUSE: Self                  = Self::from_hex_rgb("#7FFF00");
            pub const CSS_CHOCOLATE: Self                   = Self::from_hex_rgb("#D2691E");
            pub const CSS_CORAL: Self                       = Self::from_hex_rgb("#FF7F50");
            pub const CSS_CORNFLOWERBLUE: Self              = Self::from_hex_rgb("#6495ED");
            pub const CSS_CORNSILK: Self                    = Self::from_hex_rgb("#FFF8DC");
            pub const CSS_CRIMSON: Self                     = Self::from_hex_rgb("#DC143C");
            pub const CSS_CYAN: Self                        = Self::from_hex_rgb("#00FFFF");
            pub const CSS_DARKBLUE: Self                    = Self::from_hex_rgb("#00008B");
            pub const CSS_DARKCYAN: Self                    = Self::from_hex_rgb("#008B8B");
            pub const CSS_DARKGOLDENROD: Self               = Self::from_hex_rgb("#B8860B");
            pub const CSS_DARKGRAY: Self                    = Self::from_hex_rgb("#A9A9A9");
            pub const CSS_DARKGREEN: Self                   = Self::from_hex_rgb("#006400");
            pub const CSS_DARKKHAKI: Self                   = Self::from_hex_rgb("#BDB76B");
            pub const CSS_DARKMAGENTA: Self                 = Self::from_hex_rgb("#8B008B");
            pub const CSS_DARKOLIVEGREEN: Self              = Self::from_hex_rgb("#556B2F");
            pub const CSS_DARKORANGE: Self                  = Self::from_hex_rgb("#FF8C00");
            pub const CSS_DARKORCHID: Self                  = Self::from_hex_rgb("#9932CC");
            pub const CSS_DARKRED: Self                     = Self::from_hex_rgb("#8B0000");
            pub const CSS_DARKSALMON: Self                  = Self::from_hex_rgb("#E9967A");
            pub const CSS_DARKSEAGREEN: Self                = Self::from_hex_rgb("#8FBC8F");
            pub const CSS_DARKSLATEBLUE: Self               = Self::from_hex_rgb("#483D8B");
            pub const CSS_DARKSLATEGRAY: Self               = Self::from_hex_rgb("#2F4F4F");
            pub const CSS_DARKTURQUOISE: Self               = Self::from_hex_rgb("#00CED1");
            pub const CSS_DARKVIOLET: Self                  = Self::from_hex_rgb("#9400D3");
            pub const CSS_DEEPPINK: Self                    = Self::from_hex_rgb("#FF1493");
            pub const CSS_DEEPSKYBLUE: Self                 = Self::from_hex_rgb("#00BFFF");
            pub const CSS_DIMGRAY: Self                     = Self::from_hex_rgb("#696969");
            pub const CSS_DODGERBLUE: Self                  = Self::from_hex_rgb("#1E90FF");
            pub const CSS_FIREBRICK: Self                   = Self::from_hex_rgb("#B22222");
            pub const CSS_FLORALWHITE: Self                 = Self::from_hex_rgb("#FFFAF0");
            pub const CSS_FORESTGREEN: Self                 = Self::from_hex_rgb("#228B22");
            pub const CSS_FUCHSIA: Self                     = Self::from_hex_rgb("#FF00FF");
            pub const CSS_GAINSBORO: Self                   = Self::from_hex_rgb("#DCDCDC");
            pub const CSS_GHOSTWHITE: Self                  = Self::from_hex_rgb("#F8F8FF");
            pub const CSS_GOLD: Self                        = Self::from_hex_rgb("#FFD700");
            pub const CSS_GOLDENROD: Self                   = Self::from_hex_rgb("#DAA520");
            pub const CSS_GRAY: Self                        = Self::from_hex_rgb("#808080");
            pub const CSS_GREEN: Self                       = Self::from_hex_rgb("#008000");
            pub const CSS_GREENYELLOW: Self                 = Self::from_hex_rgb("#ADFF2F");
            pub const CSS_HONEYDEW: Self                    = Self::from_hex_rgb("#F0FFF0");
            pub const CSS_HOTPINK: Self                     = Self::from_hex_rgb("#FF69B4");
            pub const CSS_INDIANRED: Self                   = Self::from_hex_rgb("#CD5C5C");
            pub const CSS_INDIGO: Self                      = Self::from_hex_rgb("#4B0082");
            pub const CSS_IVORY: Self                       = Self::from_hex_rgb("#FFFFF0");
            pub const CSS_KHAKI: Self                       = Self::from_hex_rgb("#F0E68C");
            pub const CSS_LAVENDER: Self                    = Self::from_hex_rgb("#E6E6FA");
            pub const CSS_LAVENDERBLUSH: Self               = Self::from_hex_rgb("#FFF0F5");
            pub const CSS_LAWNGREEN: Self                   = Self::from_hex_rgb("#7CFC00");
            pub const CSS_LEMONCHIFFON: Self                = Self::from_hex_rgb("#FFFACD");
            pub const CSS_LIGHTBLUE: Self                   = Self::from_hex_rgb("#ADD8E6");
            pub const CSS_LIGHTCORAL: Self                  = Self::from_hex_rgb("#F08080");
            pub const CSS_LIGHTCYAN: Self                   = Self::from_hex_rgb("#E0FFFF");
            pub const CSS_LIGHTGOLDENRODYELLOW: Self        = Self::from_hex_rgb("#FAFAD2");
            pub const CSS_LIGHTGRAY: Self                   = Self::from_hex_rgb("#D3D3D3");
            pub const CSS_LIGHTGREEN: Self                  = Self::from_hex_rgb("#90EE90");
            pub const CSS_LIGHTPINK: Self                   = Self::from_hex_rgb("#FFB6C1");
            pub const CSS_LIGHTSALMON: Self                 = Self::from_hex_rgb("#FFA07A");
            pub const CSS_LIGHTSEAGREEN: Self               = Self::from_hex_rgb("#20B2AA");
            pub const CSS_LIGHTSKYBLUE: Self                = Self::from_hex_rgb("#87CEFA");
            pub const CSS_LIGHTSLATEGRAY: Self              = Self::from_hex_rgb("#778899");
            pub const CSS_LIGHTSTEELBLUE: Self              = Self::from_hex_rgb("#B0C4DE");
            pub const CSS_LIGHTYELLOW: Self                 = Self::from_hex_rgb("#FFFFE0");
            pub const CSS_LIME: Self                        = Self::from_hex_rgb("#00FF00");
            pub const CSS_LIMEGREEN: Self                   = Self::from_hex_rgb("#32CD32");
            pub const CSS_LINEN: Self                       = Self::from_hex_rgb("#FAF0E6");
            pub const CSS_MAGENTA: Self                     = Self::from_hex_rgb("#FF00FF");
            pub const CSS_MAROON: Self                      = Self::from_hex_rgb("#800000");
            pub const CSS_MEDIUMAQUAMARINE: Self            = Self::from_hex_rgb("#66CDAA");
            pub const CSS_MEDIUMBLUE: Self                  = Self::from_hex_rgb("#0000CD");
            pub const CSS_MEDIUMORCHID: Self                = Self::from_hex_rgb("#BA55D3");
            pub const CSS_MEDIUMPURPLE: Self                = Self::from_hex_rgb("#9370DB");
            pub const CSS_MEDIUMSEAGREEN: Self              = Self::from_hex_rgb("#3CB371");
            pub const CSS_MEDIUMSLATEBLUE: Self             = Self::from_hex_rgb("#7B68EE");
            pub const CSS_MEDIUMSPRINGGREEN: Self           = Self::from_hex_rgb("#00FA9A");
            pub const CSS_MEDIUMTURQUOISE: Self             = Self::from_hex_rgb("#48D1CC");
            pub const CSS_MEDIUMVIOLETRED: Self             = Self::from_hex_rgb("#C71585");
            pub const CSS_MIDNIGHTBLUE: Self                = Self::from_hex_rgb("#191970");
            pub const CSS_MINTCREAM: Self                   = Self::from_hex_rgb("#F5FFFA");
            pub const CSS_MISTYROSE: Self                   = Self::from_hex_rgb("#FFE4E1");
            pub const CSS_MOCCASIN: Self                    = Self::from_hex_rgb("#FFE4B5");
            pub const CSS_NAVAJOWHITE: Self                 = Self::from_hex_rgb("#FFDEAD");
            pub const CSS_NAVY: Self                        = Self::from_hex_rgb("#000080");
            pub const CSS_OLDLACE: Self                     = Self::from_hex_rgb("#FDF5E6");
            pub const CSS_OLIVE: Self                       = Self::from_hex_rgb("#808000");
            pub const CSS_OLIVEDRAB: Self                   = Self::from_hex_rgb("#6B8E23");
            pub const CSS_ORANGE: Self                      = Self::from_hex_rgb("#FFA500");
            pub const CSS_ORANGERED: Self                   = Self::from_hex_rgb("#FF4500");
            pub const CSS_ORCHID: Self                      = Self::from_hex_rgb("#DA70D6");
            pub const CSS_PALEGOLDENROD: Self               = Self::from_hex_rgb("#EEE8AA");
            pub const CSS_PALEGREEN: Self                   = Self::from_hex_rgb("#98FB98");
            pub const CSS_PALETURQUOISE: Self               = Self::from_hex_rgb("#AFEEEE");
            pub const CSS_PALEVIOLETRED: Self               = Self::from_hex_rgb("#DB7093");
            pub const CSS_PAPAYAWHIP: Self                  = Self::from_hex_rgb("#FFEFD5");
            pub const CSS_PEACHPUFF: Self                   = Self::from_hex_rgb("#FFDAB9");
            pub const CSS_PERU: Self                        = Self::from_hex_rgb("#CD853F");
            pub const CSS_PINK: Self                        = Self::from_hex_rgb("#FFC0CB");
            pub const CSS_PLUM: Self                        = Self::from_hex_rgb("#DDA0DD");
            pub const CSS_POWDERBLUE: Self                  = Self::from_hex_rgb("#B0E0E6");
            pub const CSS_PURPLE: Self                      = Self::from_hex_rgb("#800080");
            pub const CSS_REBECCAPURPLE: Self               = Self::from_hex_rgb("#663399");
            pub const CSS_RED: Self                         = Self::from_hex_rgb("#FF0000");
            pub const CSS_ROSYBROWN: Self                   = Self::from_hex_rgb("#BC8F8F");
            pub const CSS_ROYALBLUE: Self                   = Self::from_hex_rgb("#4169E1");
            pub const CSS_SADDLEBROWN: Self                 = Self::from_hex_rgb("#8B4513");
            pub const CSS_SALMON: Self                      = Self::from_hex_rgb("#FA8072");
            pub const CSS_SANDYBROWN: Self                  = Self::from_hex_rgb("#F4A460");
            pub const CSS_SEAGREEN: Self                    = Self::from_hex_rgb("#2E8B57");
            pub const CSS_SEASHELL: Self                    = Self::from_hex_rgb("#FFF5EE");
            pub const CSS_SIENNA: Self                      = Self::from_hex_rgb("#A0522D");
            pub const CSS_SILVER: Self                      = Self::from_hex_rgb("#C0C0C0");
            pub const CSS_SKYBLUE: Self                     = Self::from_hex_rgb("#87CEEB");
            pub const CSS_SLATEBLUE: Self                   = Self::from_hex_rgb("#6A5ACD");
            pub const CSS_SLATEGRAY: Self                   = Self::from_hex_rgb("#708090");
            pub const CSS_SNOW: Self                        = Self::from_hex_rgb("#FFFAFA");
            pub const CSS_SPRINGGREEN: Self                 = Self::from_hex_rgb("#00FF7F");
            pub const CSS_STEELBLUE: Self                   = Self::from_hex_rgb("#4682B4");
            pub const CSS_TAN: Self                         = Self::from_hex_rgb("#D2B48C");
            pub const CSS_TEAL: Self                        = Self::from_hex_rgb("#008080");
            pub const CSS_THISTLE: Self                     = Self::from_hex_rgb("#D8BFD8");
            pub const CSS_TOMATO: Self                      = Self::from_hex_rgb("#FF6347");
            pub const CSS_TURQUOISE: Self                   = Self::from_hex_rgb("#40E0D0");
            pub const CSS_VIOLET: Self                      = Self::from_hex_rgb("#EE82EE");
            pub const CSS_WHEAT: Self                       = Self::from_hex_rgb("#F5DEB3");
            pub const CSS_WHITE: Self                       = Self::from_hex_rgb("#FFFFFF");
            pub const CSS_WHITESMOKE: Self                  = Self::from_hex_rgb("#F5F5F5");
            pub const CSS_YELLOW: Self                      = Self::from_hex_rgb("#FFFF00");
            pub const CSS_YELLOWGREEN: Self                 = Self::from_hex_rgb("#9ACD32");
            pub const BLACK: Self           = Self::rgb (        0.0,         0.0,         0.0                );
            pub const WHITE: Self           = Self::rgb (        1.0,         1.0,         1.0                );
            pub const TRANSPARENT: Self                 = Self::rgba(        0.0,         0.0,         0.0,            0.0);
            pub const RED: Self             = Self::rgb (        1.0,         0.0,         0.0                );
            pub const LIME: Self           = Self::rgb (        0.0,         1.0,         0.0                );
            pub const GREEN: Self           = Self::rgb (        0.0,         1.0,         0.0                );
            pub const BLUE: Self            = Self::rgb (        0.0,         0.0,         1.0                );
            pub const YELLOW: Self          = Self::rgb (        1.0,         1.0,         0.0                );
            pub const PURPLE: Self          = Self::rgb (        1.0,         0.0,         1.0                );
            pub const CYAN: Self            = Self::rgb (        0.0,         1.0,         1.0                );
            pub const AQUA: Self            = Self::rgb (        0.0,         1.0,         1.0                );
        }
    };
}

color_consts!(Color);
color_consts!(ColorF64);

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_color_consts() {
        assert_eq!(Color::RED, Color::from_hex_rgb("#FF0000"));
        assert_eq!(ColorF64::LIME, ColorF64::from_hex_rgb("#00ff00"));
        assert_eq!(Color::BLUE, Color::from_hex_rgb("#0000FF"));
        assert_eq!(ColorF64::WHITE, ColorF64::from_hex_rgb("#FFFFFF"));
        assert_eq!(Color::BLACK, Color::from_hex_rgb("#000000"));
    }
}