//! `KeyCode` ↔ 表下标 常量转换表（生成自 winit 0.30.13 的 `KeyCode` 枚举）。
//!
//! winit 的 `KeyCode` 是 `#[non_exhaustive]` 无字段枚举，判别值从 0 起按声明顺序连续
//! （首个变体 `Backquote` = 0，末个 `F35` = `KEY_CODE_COUNT - 1` = 193）。本模块用显式 `const fn match`
//! 完成 枚举 ⇄ 数字 双向转换，供 [`crate::KeyboardInput`] 的 `[KeyState; 256]`
//! 按键表（下标 = 数字）使用——不依赖 `as usize` 与 unsafe。
//!
//! **同步提示**：升级 winit 后若 `KeyCode` 变体变化，`key_code_index` 的穷尽 match
//! 会因新增变体而编译失败（`#[non_exhaustive]` 通配臂除外），届时请重新生成本文件。

use winit::keyboard::KeyCode;

/// `KeyCode` 变体总数（= 最大下标 + 1；`[KeyState; 256]` 只需前 `KEY_CODE_COUNT` 个槽位）。
pub const KEY_CODE_COUNT: usize = 194;

/// `KeyCode` → 表下标（= 枚举判别值，O(1)）。
#[inline]
pub const fn key_code_index(k: KeyCode) -> usize {
    match k {
        KeyCode::Backquote => 0,
        KeyCode::Backslash => 1,
        KeyCode::BracketLeft => 2,
        KeyCode::BracketRight => 3,
        KeyCode::Comma => 4,
        KeyCode::Digit0 => 5,
        KeyCode::Digit1 => 6,
        KeyCode::Digit2 => 7,
        KeyCode::Digit3 => 8,
        KeyCode::Digit4 => 9,
        KeyCode::Digit5 => 10,
        KeyCode::Digit6 => 11,
        KeyCode::Digit7 => 12,
        KeyCode::Digit8 => 13,
        KeyCode::Digit9 => 14,
        KeyCode::Equal => 15,
        KeyCode::IntlBackslash => 16,
        KeyCode::IntlRo => 17,
        KeyCode::IntlYen => 18,
        KeyCode::KeyA => 19,
        KeyCode::KeyB => 20,
        KeyCode::KeyC => 21,
        KeyCode::KeyD => 22,
        KeyCode::KeyE => 23,
        KeyCode::KeyF => 24,
        KeyCode::KeyG => 25,
        KeyCode::KeyH => 26,
        KeyCode::KeyI => 27,
        KeyCode::KeyJ => 28,
        KeyCode::KeyK => 29,
        KeyCode::KeyL => 30,
        KeyCode::KeyM => 31,
        KeyCode::KeyN => 32,
        KeyCode::KeyO => 33,
        KeyCode::KeyP => 34,
        KeyCode::KeyQ => 35,
        KeyCode::KeyR => 36,
        KeyCode::KeyS => 37,
        KeyCode::KeyT => 38,
        KeyCode::KeyU => 39,
        KeyCode::KeyV => 40,
        KeyCode::KeyW => 41,
        KeyCode::KeyX => 42,
        KeyCode::KeyY => 43,
        KeyCode::KeyZ => 44,
        KeyCode::Minus => 45,
        KeyCode::Period => 46,
        KeyCode::Quote => 47,
        KeyCode::Semicolon => 48,
        KeyCode::Slash => 49,
        KeyCode::AltLeft => 50,
        KeyCode::AltRight => 51,
        KeyCode::Backspace => 52,
        KeyCode::CapsLock => 53,
        KeyCode::ContextMenu => 54,
        KeyCode::ControlLeft => 55,
        KeyCode::ControlRight => 56,
        KeyCode::Enter => 57,
        KeyCode::SuperLeft => 58,
        KeyCode::SuperRight => 59,
        KeyCode::ShiftLeft => 60,
        KeyCode::ShiftRight => 61,
        KeyCode::Space => 62,
        KeyCode::Tab => 63,
        KeyCode::Convert => 64,
        KeyCode::KanaMode => 65,
        KeyCode::Lang1 => 66,
        KeyCode::Lang2 => 67,
        KeyCode::Lang3 => 68,
        KeyCode::Lang4 => 69,
        KeyCode::Lang5 => 70,
        KeyCode::NonConvert => 71,
        KeyCode::Delete => 72,
        KeyCode::End => 73,
        KeyCode::Help => 74,
        KeyCode::Home => 75,
        KeyCode::Insert => 76,
        KeyCode::PageDown => 77,
        KeyCode::PageUp => 78,
        KeyCode::ArrowDown => 79,
        KeyCode::ArrowLeft => 80,
        KeyCode::ArrowRight => 81,
        KeyCode::ArrowUp => 82,
        KeyCode::NumLock => 83,
        KeyCode::Numpad0 => 84,
        KeyCode::Numpad1 => 85,
        KeyCode::Numpad2 => 86,
        KeyCode::Numpad3 => 87,
        KeyCode::Numpad4 => 88,
        KeyCode::Numpad5 => 89,
        KeyCode::Numpad6 => 90,
        KeyCode::Numpad7 => 91,
        KeyCode::Numpad8 => 92,
        KeyCode::Numpad9 => 93,
        KeyCode::NumpadAdd => 94,
        KeyCode::NumpadBackspace => 95,
        KeyCode::NumpadClear => 96,
        KeyCode::NumpadClearEntry => 97,
        KeyCode::NumpadComma => 98,
        KeyCode::NumpadDecimal => 99,
        KeyCode::NumpadDivide => 100,
        KeyCode::NumpadEnter => 101,
        KeyCode::NumpadEqual => 102,
        KeyCode::NumpadHash => 103,
        KeyCode::NumpadMemoryAdd => 104,
        KeyCode::NumpadMemoryClear => 105,
        KeyCode::NumpadMemoryRecall => 106,
        KeyCode::NumpadMemoryStore => 107,
        KeyCode::NumpadMemorySubtract => 108,
        KeyCode::NumpadMultiply => 109,
        KeyCode::NumpadParenLeft => 110,
        KeyCode::NumpadParenRight => 111,
        KeyCode::NumpadStar => 112,
        KeyCode::NumpadSubtract => 113,
        KeyCode::Escape => 114,
        KeyCode::Fn => 115,
        KeyCode::FnLock => 116,
        KeyCode::PrintScreen => 117,
        KeyCode::ScrollLock => 118,
        KeyCode::Pause => 119,
        KeyCode::BrowserBack => 120,
        KeyCode::BrowserFavorites => 121,
        KeyCode::BrowserForward => 122,
        KeyCode::BrowserHome => 123,
        KeyCode::BrowserRefresh => 124,
        KeyCode::BrowserSearch => 125,
        KeyCode::BrowserStop => 126,
        KeyCode::Eject => 127,
        KeyCode::LaunchApp1 => 128,
        KeyCode::LaunchApp2 => 129,
        KeyCode::LaunchMail => 130,
        KeyCode::MediaPlayPause => 131,
        KeyCode::MediaSelect => 132,
        KeyCode::MediaStop => 133,
        KeyCode::MediaTrackNext => 134,
        KeyCode::MediaTrackPrevious => 135,
        KeyCode::Power => 136,
        KeyCode::Sleep => 137,
        KeyCode::AudioVolumeDown => 138,
        KeyCode::AudioVolumeMute => 139,
        KeyCode::AudioVolumeUp => 140,
        KeyCode::WakeUp => 141,
        KeyCode::Meta => 142,
        KeyCode::Hyper => 143,
        KeyCode::Turbo => 144,
        KeyCode::Abort => 145,
        KeyCode::Resume => 146,
        KeyCode::Suspend => 147,
        KeyCode::Again => 148,
        KeyCode::Copy => 149,
        KeyCode::Cut => 150,
        KeyCode::Find => 151,
        KeyCode::Open => 152,
        KeyCode::Paste => 153,
        KeyCode::Props => 154,
        KeyCode::Select => 155,
        KeyCode::Undo => 156,
        KeyCode::Hiragana => 157,
        KeyCode::Katakana => 158,
        KeyCode::F1 => 159,
        KeyCode::F2 => 160,
        KeyCode::F3 => 161,
        KeyCode::F4 => 162,
        KeyCode::F5 => 163,
        KeyCode::F6 => 164,
        KeyCode::F7 => 165,
        KeyCode::F8 => 166,
        KeyCode::F9 => 167,
        KeyCode::F10 => 168,
        KeyCode::F11 => 169,
        KeyCode::F12 => 170,
        KeyCode::F13 => 171,
        KeyCode::F14 => 172,
        KeyCode::F15 => 173,
        KeyCode::F16 => 174,
        KeyCode::F17 => 175,
        KeyCode::F18 => 176,
        KeyCode::F19 => 177,
        KeyCode::F20 => 178,
        KeyCode::F21 => 179,
        KeyCode::F22 => 180,
        KeyCode::F23 => 181,
        KeyCode::F24 => 182,
        KeyCode::F25 => 183,
        KeyCode::F26 => 184,
        KeyCode::F27 => 185,
        KeyCode::F28 => 186,
        KeyCode::F29 => 187,
        KeyCode::F30 => 188,
        KeyCode::F31 => 189,
        KeyCode::F32 => 190,
        KeyCode::F33 => 191,
        KeyCode::F34 => 192,
        KeyCode::F35 => 193,
        // `#[non_exhaustive]` 要求通配臂；winit 新增变体时在此显式失败（编译期常量 panic）。
        _ => panic!("KeyCode 变体未收录进 key_code 表：请重新生成 key_code.rs"),
    }
}

/// 表下标 → `KeyCode`（仅当 `i < KEY_CODE_COUNT` 时有效，越界 panic）。
#[inline]
pub const fn key_code_from_index(i: usize) -> KeyCode {
    match i {
        0 => KeyCode::Backquote,
        1 => KeyCode::Backslash,
        2 => KeyCode::BracketLeft,
        3 => KeyCode::BracketRight,
        4 => KeyCode::Comma,
        5 => KeyCode::Digit0,
        6 => KeyCode::Digit1,
        7 => KeyCode::Digit2,
        8 => KeyCode::Digit3,
        9 => KeyCode::Digit4,
        10 => KeyCode::Digit5,
        11 => KeyCode::Digit6,
        12 => KeyCode::Digit7,
        13 => KeyCode::Digit8,
        14 => KeyCode::Digit9,
        15 => KeyCode::Equal,
        16 => KeyCode::IntlBackslash,
        17 => KeyCode::IntlRo,
        18 => KeyCode::IntlYen,
        19 => KeyCode::KeyA,
        20 => KeyCode::KeyB,
        21 => KeyCode::KeyC,
        22 => KeyCode::KeyD,
        23 => KeyCode::KeyE,
        24 => KeyCode::KeyF,
        25 => KeyCode::KeyG,
        26 => KeyCode::KeyH,
        27 => KeyCode::KeyI,
        28 => KeyCode::KeyJ,
        29 => KeyCode::KeyK,
        30 => KeyCode::KeyL,
        31 => KeyCode::KeyM,
        32 => KeyCode::KeyN,
        33 => KeyCode::KeyO,
        34 => KeyCode::KeyP,
        35 => KeyCode::KeyQ,
        36 => KeyCode::KeyR,
        37 => KeyCode::KeyS,
        38 => KeyCode::KeyT,
        39 => KeyCode::KeyU,
        40 => KeyCode::KeyV,
        41 => KeyCode::KeyW,
        42 => KeyCode::KeyX,
        43 => KeyCode::KeyY,
        44 => KeyCode::KeyZ,
        45 => KeyCode::Minus,
        46 => KeyCode::Period,
        47 => KeyCode::Quote,
        48 => KeyCode::Semicolon,
        49 => KeyCode::Slash,
        50 => KeyCode::AltLeft,
        51 => KeyCode::AltRight,
        52 => KeyCode::Backspace,
        53 => KeyCode::CapsLock,
        54 => KeyCode::ContextMenu,
        55 => KeyCode::ControlLeft,
        56 => KeyCode::ControlRight,
        57 => KeyCode::Enter,
        58 => KeyCode::SuperLeft,
        59 => KeyCode::SuperRight,
        60 => KeyCode::ShiftLeft,
        61 => KeyCode::ShiftRight,
        62 => KeyCode::Space,
        63 => KeyCode::Tab,
        64 => KeyCode::Convert,
        65 => KeyCode::KanaMode,
        66 => KeyCode::Lang1,
        67 => KeyCode::Lang2,
        68 => KeyCode::Lang3,
        69 => KeyCode::Lang4,
        70 => KeyCode::Lang5,
        71 => KeyCode::NonConvert,
        72 => KeyCode::Delete,
        73 => KeyCode::End,
        74 => KeyCode::Help,
        75 => KeyCode::Home,
        76 => KeyCode::Insert,
        77 => KeyCode::PageDown,
        78 => KeyCode::PageUp,
        79 => KeyCode::ArrowDown,
        80 => KeyCode::ArrowLeft,
        81 => KeyCode::ArrowRight,
        82 => KeyCode::ArrowUp,
        83 => KeyCode::NumLock,
        84 => KeyCode::Numpad0,
        85 => KeyCode::Numpad1,
        86 => KeyCode::Numpad2,
        87 => KeyCode::Numpad3,
        88 => KeyCode::Numpad4,
        89 => KeyCode::Numpad5,
        90 => KeyCode::Numpad6,
        91 => KeyCode::Numpad7,
        92 => KeyCode::Numpad8,
        93 => KeyCode::Numpad9,
        94 => KeyCode::NumpadAdd,
        95 => KeyCode::NumpadBackspace,
        96 => KeyCode::NumpadClear,
        97 => KeyCode::NumpadClearEntry,
        98 => KeyCode::NumpadComma,
        99 => KeyCode::NumpadDecimal,
        100 => KeyCode::NumpadDivide,
        101 => KeyCode::NumpadEnter,
        102 => KeyCode::NumpadEqual,
        103 => KeyCode::NumpadHash,
        104 => KeyCode::NumpadMemoryAdd,
        105 => KeyCode::NumpadMemoryClear,
        106 => KeyCode::NumpadMemoryRecall,
        107 => KeyCode::NumpadMemoryStore,
        108 => KeyCode::NumpadMemorySubtract,
        109 => KeyCode::NumpadMultiply,
        110 => KeyCode::NumpadParenLeft,
        111 => KeyCode::NumpadParenRight,
        112 => KeyCode::NumpadStar,
        113 => KeyCode::NumpadSubtract,
        114 => KeyCode::Escape,
        115 => KeyCode::Fn,
        116 => KeyCode::FnLock,
        117 => KeyCode::PrintScreen,
        118 => KeyCode::ScrollLock,
        119 => KeyCode::Pause,
        120 => KeyCode::BrowserBack,
        121 => KeyCode::BrowserFavorites,
        122 => KeyCode::BrowserForward,
        123 => KeyCode::BrowserHome,
        124 => KeyCode::BrowserRefresh,
        125 => KeyCode::BrowserSearch,
        126 => KeyCode::BrowserStop,
        127 => KeyCode::Eject,
        128 => KeyCode::LaunchApp1,
        129 => KeyCode::LaunchApp2,
        130 => KeyCode::LaunchMail,
        131 => KeyCode::MediaPlayPause,
        132 => KeyCode::MediaSelect,
        133 => KeyCode::MediaStop,
        134 => KeyCode::MediaTrackNext,
        135 => KeyCode::MediaTrackPrevious,
        136 => KeyCode::Power,
        137 => KeyCode::Sleep,
        138 => KeyCode::AudioVolumeDown,
        139 => KeyCode::AudioVolumeMute,
        140 => KeyCode::AudioVolumeUp,
        141 => KeyCode::WakeUp,
        142 => KeyCode::Meta,
        143 => KeyCode::Hyper,
        144 => KeyCode::Turbo,
        145 => KeyCode::Abort,
        146 => KeyCode::Resume,
        147 => KeyCode::Suspend,
        148 => KeyCode::Again,
        149 => KeyCode::Copy,
        150 => KeyCode::Cut,
        151 => KeyCode::Find,
        152 => KeyCode::Open,
        153 => KeyCode::Paste,
        154 => KeyCode::Props,
        155 => KeyCode::Select,
        156 => KeyCode::Undo,
        157 => KeyCode::Hiragana,
        158 => KeyCode::Katakana,
        159 => KeyCode::F1,
        160 => KeyCode::F2,
        161 => KeyCode::F3,
        162 => KeyCode::F4,
        163 => KeyCode::F5,
        164 => KeyCode::F6,
        165 => KeyCode::F7,
        166 => KeyCode::F8,
        167 => KeyCode::F9,
        168 => KeyCode::F10,
        169 => KeyCode::F11,
        170 => KeyCode::F12,
        171 => KeyCode::F13,
        172 => KeyCode::F14,
        173 => KeyCode::F15,
        174 => KeyCode::F16,
        175 => KeyCode::F17,
        176 => KeyCode::F18,
        177 => KeyCode::F19,
        178 => KeyCode::F20,
        179 => KeyCode::F21,
        180 => KeyCode::F22,
        181 => KeyCode::F23,
        182 => KeyCode::F24,
        183 => KeyCode::F25,
        184 => KeyCode::F26,
        185 => KeyCode::F27,
        186 => KeyCode::F28,
        187 => KeyCode::F29,
        188 => KeyCode::F30,
        189 => KeyCode::F31,
        190 => KeyCode::F32,
        191 => KeyCode::F33,
        192 => KeyCode::F34,
        193 => KeyCode::F35,
        _ => panic!("key_code_from_index: 越界下标（应 < KEY_CODE_COUNT）"),
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    /// 抽查首/中/末键：数字与编译器判别值（`as usize`）一致。
    #[test]
    fn index_matches_discriminant() {
        assert_eq!(key_code_index(KeyCode::Backquote), KeyCode::Backquote as usize);
        assert_eq!(key_code_index(KeyCode::KeyA), KeyCode::KeyA as usize);
        assert_eq!(key_code_index(KeyCode::Space), KeyCode::Space as usize);
        assert_eq!(key_code_index(KeyCode::Enter), KeyCode::Enter as usize);
        assert_eq!(key_code_index(KeyCode::F35), KeyCode::F35 as usize);
        assert_eq!(key_code_index(KeyCode::Backquote), 0);
        assert_eq!(key_code_index(KeyCode::F35), KEY_CODE_COUNT - 1);
    }

    /// 全量往返：`from_index(index(k)) == k` 对每个变体成立。
    #[test]
    fn from_index_round_trips() {
        for i in 0..KEY_CODE_COUNT {
            assert_eq!(key_code_index(key_code_from_index(i)), i);
        }
    }

    /// 越界下标 → panic。
    #[test]
    fn from_index_out_of_range_panics() {
        assert!(std::panic::catch_unwind(|| key_code_from_index(KEY_CODE_COUNT)).is_err());
        assert!(std::panic::catch_unwind(|| key_code_from_index(usize::MAX)).is_err());
    }
}
